import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:social_media/auth/auth.dart';
import 'package:social_media/pages/post_page.dart';

import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'services/notification_service.dart';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  // Ensure Flutter engine is ready before calling native plugins.
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialise Firebase (must come before any Firebase service).
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 2. Initialise NotificationService immediately after Firebase.
  //    This registers the background handler, requests permissions,
  //    sets up local notifications, and retrieves the FCM token.
  await NotificationService.instance
      .init(); //*“Start listening for notifications as soon as app launches”

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'SafeSpot',
      navigatorKey: navigatorKey,
      routes: {'/post': (context) => PostPage()},

      home: const Auth(),
    );
  }
}
